server {
    listen 4321;
    server_name localhost;

    # Evitar que Nginx redirija a http://localhost/ sin el puerto del host (:4321)
    port_in_redirect off;
    absolute_redirect off;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Compresión gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;

    location / {
        try_files $uri $uri/ $uri.html /index.html;
    }

    # Caché de activos estáticos
    location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|woff|woff2)$ {
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }

    error_page 404 /404.html;
}
